// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgedirwipqtfqkyvoojk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZWRpcndpcHF0ZnFreXZvb2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NjQyNDUsImV4cCI6MjA4OTI0MDI0NX0.e4Dgs8Hu8rmmZ6BwOnrufccl_MnSBPBiz6CIdz27KfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});